a = int(input())
b = int(input())
c = int(input())
mul = a*b*c
mul = str(mul)
list_mul = list(mul)
print(list_mul.count('0'))
print(list_mul.count('1'))
print(list_mul.count('2'))
print(list_mul.count('3'))
print(list_mul.count('4'))
print(list_mul.count('5'))
print(list_mul.count('6'))
print(list_mul.count('7'))
print(list_mul.count('8'))
print(list_mul.count('9'))
